name: build.ci.cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: nucleotidzagent
  AZURE_WEBAPP_PACKAGE_PATH: './publish-output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: build
      run: |
          dotnet restore ./api.sln
          dotnet build ./api.sln --configuration Release
      
    - name: Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet publish ./src/api/api.csproj --configuration Release --output ./publish-output
      

    - name: 'Deploy to Azure Web App'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
